$installation = <<SCRIPT
sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"/g' /etc/default/grub
update-grub
echo "Europe/Amsterdam" | tee /etc/timezone
dpkg-reconfigure --frontend noninteractive tzdata

useradd dev -m -s /bin/bash 
usermod -G sudo dev
mkdir -p /home/dev/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxM1lW9AEOChXGk6m1dq3KZWm14IzEinXYYxIu+twwX1rOlTvt9nIV/qlCzfsdXCD4ut8KpKWNtrj5+49/rzo+147Tc/T5QuEZlY2d9j889QOrmb7y+4lcLQBp87wtn21yyamjiQjHq9REHHNt7m8negN99Cv/oTno+ib8hqxOgMqgMgG5iKKNoFQeEsON/erWzAOJrWdw+3lWFg/LwQScqOkIZSL3oSliuv47Q4eTWb5OdprX9/IIxETRKXPuosl17KQFWJMkZAxE3kQoMCIWW+tvukI8tG/C/WPEy64kGx6oBbHJyPaWpN4AvAYtAysT6YIAlfMgwbBwHl5ufafD dev@dev" >> /home/dev/.ssh/authorized_keys

sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-wily main" > /etc/apt/sources.list.d/docker.list

sudo apt-get update
sudo apt-get purge lxc-docker
sudo apt-get -y autoremove
sudo apt-get -y install docker-engine
sudo awk -i inplace '{gsub(/-H.*/,"-H tcp://192.168.168.169:2375"); print}' /lib/systemd/system/docker.service
sudo systemctl daemon-reload
sudo systemctl restart docker

reboot
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/wily64"

  config.vm.hostname = 'docker2.localdomain'
  config.vm.network 'private_network', ip: '192.168.168.169'

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.name = "vm_dev"
    vb.customize ['modifyvm', :id, '--memory', 2048]
  end

  config.vm.synced_folder "/Users/jan/dev/docker/", "/src", type: "nfs"
  config.vm.provision 'shell', inline: $installation
end

