$installation = <<SCRIPT
sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"/g' /etc/default/grub
update-grub
echo "Europe/Amsterdam" | tee /etc/timezone
dpkg-reconfigure --frontend noninteractive tzdata

sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-wily main" > /etc/apt/sources.list.d/docker.list

sudo apt-get update
sudo apt-get purge lxc-docker
sudo apt-get -y autoremove
sudo apt-get -y install docker-engine
sudo awk -i inplace '{gsub(/-H.*/,"-H tcp://192.168.168.169:2375"); print}' /lib/systemd/system/docker.service
sudo systemctl daemon-reload
sudo systemctl restart docker

reboot
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/wily64"

  config.vm.hostname = 'docker2.localdomain'
  config.vm.network 'private_network', ip: '192.168.168.169'

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.name = "aapv2"
    vb.customize ['modifyvm', :id, '--memory', 2048]
  end

  config.vm.synced_folder "/Users/jan/dev/docker/", "/src/", type: "nfs"
  config.vm.provision 'shell', inline: $installation
end
